#!/usr/bin/env bash

set -eo pipefail

: "${POSTGRES_VERSION:=17}"
: "${POSTGRES_USER:=postgres}"
: "${POSTGRES_PASSWORD:=postgres}"
: "${POSTGRES_HOST_AUTH_METHOD:=trust}"
: "${POSTGRES_ROLE_ATTRIBUTES:=LOGIN CREATEDB}"
: "${POSTGRES_EXTENSIONS:=}"

: "${EPHEMERAL_POSTGRES_AUTO_UPDATE:=1}"
: "${EPHEMERAL_POSTGRES_FORCE_BUILD:=0}"
: "${EPHEMERAL_POSTGRES_DATA_DIR:=}"
: "${EPHEMERAL_POSTGRES_LINUX_USER:=$(id -u)}"
: "${EPHEMERAL_POSTGRES_DOCKER_RUN_ARGS:=}"

if [ -f .env.sh ]; then
  echo "loading config from '.env.sh'"
  source .env.sh
fi

export POSTGRES_VERSION
export POSTGRES_USER
export POSTGRES_PASSWORD
export POSTGRES_HOST_AUTH_METHOD
export POSTGRES_ROLE_ATTRIBUTES
export POSTGRES_EXTENSIONS

export EPHEMERAL_POSTGRES_AUTO_UPDATE
export EPHEMERAL_POSTGRES_FORCE_BUILD
export EPHEMERAL_POSTGRES_DATA_DIR
export EPHEMERAL_POSTGRES_LINUX_USER
export EPHEMERAL_POSTGRES_DOCKER_RUN_ARGS
