name: Build ephemeral-postgres

on:
  push:
    branches:
    - main
  pull_request:

  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: ci (${{ matrix.postgres-version }})
    runs-on: ubuntu-latest

    env:
      EPHEMERAL_POSTGRES_AUTO_UPDATE: 0
      POSTGRES_VERSION: ${{ matrix.postgres-version }}

    strategy:
      matrix:
        postgres-version: [
          14,
          15,
          16,
          17,
          18
        ]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ephemeral-postgres ${{ matrix.postgres-version }}
        run: ./bin/build-image.sh "$POSTGRES_VERSION"

      - name: Test ephemeral-postgres ${{ matrix.postgres-version }}
        run: ./bin/test-image.sh "$POSTGRES_VERSION"
        timeout-minutes: 2

      - name: Push ephemeral-postgres ${{ matrix.postgres-version }}
        if: github.ref_name == 'main'
        run: ./bin/push-image.sh "$POSTGRES_VERSION"
