name: Build ephemeral-postgres

on:
  push:
    branches: main
  schedule:
    - cron: "0 0 * * 1"
jobs:
  login:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres-version: [
          14,
          15,
          16,
          17
        ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ephemeral-postgres ${{ matrix.postgres-version }}
        run: ./prebuild-image.sh "${{ matrix.postgres-version }}"
